### ISSUE TITLE
First render is blotchy (font loading issue?)

### ISSUE THREAD

**Issue by AaronDavidNewman** [vexflow/vexflow#86]
This might have something to do with lazy-loading the fonts.  I am using font face, as below, and starting the application after on `DOMContentLoaded` event.  It does this consistently on the first load after refreshing the browser, whether or not cache is disabled.  Subsequent loads render fine.

![image](https://github.com/vexflow/vexflow/assets/5438280/c946112d-619e-4fec-bd18-769a8fc1c72a)

``` css
@font-face {
  font-family: 'Bravura';
  src:
    url('fonts/Bravura_1.392.woff') format('woff');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```
